### ISSUE TITLE
Layout of cluster view

### ISSUE THREAD

**Issue by ckinkeldey** [FUB-HCC/IKON-projektor#121]

**Comment by ckinkeldey** [comment]
<img width="1153" alt="Untitled" src="https://user-images.githubusercontent.com/3234376/65952931-31be2f00-e443-11e9-89e3-ab3fac6f3bfe.png">

**Comment by ckinkeldey** [comment]
Cluster must be bigger and arc over whole width

**Comment by mx-e** [comment]
Implemented in #126
