### ISSUE TITLE
Display KTAs on top of line chart

### ISSUE THREAD

**Issue by ckinkeldey** [FUB-HCC/IKON-projektor#136]

**Comment by ckinkeldey** [comment]
Knowlegde transfer activities over time as circles in a matrix

**Comment by ckinkeldey** [comment]
[knowledgeTransferActivities.json.zip](https://github.com/FUB-HCC/IKON-projektor/files/3869145/knowledgeTransferActivities.json.zip)

**Comment by avvinter** [comment]
![WTA-Graph-Amount-over-Time-1](https://user-images.githubusercontent.com/44524000/69328119-faa01900-0c4e-11ea-9201-6027320e5d58.png)
![WTA-Graph-Amount-over-Time-2](https://user-images.githubusercontent.com/44524000/69328120-faa01900-0c4e-11ea-9146-a1396dbeb375.png)

**Comment by ckinkeldey** [comment]
Cool. We will need proper gridding in the matrix on top (in order to allocate the lines properly)

**Comment by avvinter** [comment]
Do you mean horizontal lines in addition to the vertical ones in the upper graph where the formats are listet?

**Comment by ckinkeldey** [comment]
Yes.

**Comment by avvinter** [comment]
which formats do you prefer? only any 15 from all formats or 15 specific?

**Comment by ckinkeldey** [comment]
Currently, we have 12 target groups that are covered.

**Comment by ckinkeldey** [comment]
Current situation:
![Screenshot 2019-11-21 12 03 46](https://user-images.githubusercontent.com/3234376/69332497-1c9d9980-0c57-11ea-9e04-16e0951d0945.png)

**Comment by avvinter** [comment]
grid like that?:
![WTA-Graph-Amount-over-Time-3](https://user-images.githubusercontent.com/44524000/69334334-c2063c80-0c5a-11ea-86e2-77e081129f60.png)

**Comment by lillijo** [comment]
should the colors (and lines) be taken from clusters then?

**Comment by lillijo** [comment]
This is what it looks now. 

![Screenshot from 2019-11-25 18-02-18](https://user-images.githubusercontent.com/38139300/69561510-cc536e00-0fad-11ea-9aca-41b06226cf99.png)
