### ISSUE TITLE
Cluster Visualization: Tiled and Colored Overlay for Cluster Groups

### ISSUE THREAD

**Issue by jessebenjamin** [FUB-HCC/IKON-projektor#143]
- [ ] first draft
- [ ] tbd

**Comment by avvinter** [comment]
20, 30 und 40% transparency:
![Multicolor-Vis-Test-2-Kachel-20](https://user-images.githubusercontent.com/44524000/69799356-68aa8a00-11d3-11ea-82a8-c58e9eadbc08.png)
![Multicolor-Vis-Test-2-Kachel-30](https://user-images.githubusercontent.com/44524000/69799357-68aa8a00-11d3-11ea-84ad-76e79b319ea5.png)
![Multicolor-Vis-Test-2-Kachel-40](https://user-images.githubusercontent.com/44524000/69799358-69432080-11d3-11ea-9766-cf0528c6e950.png)

**Comment by avvinter** [comment]
trial with mastered uncertainty map:
![Multicolor-Vis-Test-2-Kachel-Rastermap](https://user-images.githubusercontent.com/44524000/69799398-811aa480-11d3-11ea-9e1c-c73fe8011768.png)
