### ISSUE TITLE
Check performance issues

### ISSUE THREAD

**Issue by ckinkeldey** [FUB-HCC/IKON-projektor#145]

**Comment by mx-e** [comment]
created 145-check-performance issues to deal with the matter

**Comment by mx-e** [comment]
Suggestions:

- the render loop of a class is called A LOT, so everything in there is computed like 10 times when you do a mouse-over and something gets highlighted. Therefore only things that need to be computed constantly should be in there. For everything else, there are lifecycle-methods (or the map-state-to-props-method in Redux)

For detailed info on lifecycle methods see here: https://programmingwithmosh.com/javascript/react-lifecycle-methods/

**Comment by mx-e** [comment]
Other than that, i think the interpolation of spans a lot of complicated svg objects, that might be a problem in itself. If issues persist after the branch was merged and the previously outlined steps have been taken, the goal should be to reduce this complexity. Here i am not super sure what i am talking about, but reducing the number of points given from the backend should make interpolation much simpler, and therefore reduce the compute time for the heat map significantly and - i assume - will also lead to simpler paths. To which degree this can be done without degrading the precision of the heat map needs to be tested.
