### ISSUE TITLE
Legends cluster view

### ISSUE THREAD

**Issue by ckinkeldey** [FUB-HCC/IKON-projektor#149]

**Comment by ckinkeldey** [comment]
![](https://files.slack.com/files-pri/T02CX4EB0-FR7AHMXU3/screenshot_from_2019-12-11_11-35-48.png)

**Comment by ckinkeldey** [comment]
![Screenshot from 2019-12-11 11-35-48](https://user-images.githubusercontent.com/3234376/70614642-2e95ab00-1c0b-11ea-93ba-a4e5f23280d4.png)

**Comment by avvinter** [comment]
einfache Legende:
![IKON-Legende-Interface-1](https://user-images.githubusercontent.com/44524000/70620369-6145a080-1c17-11ea-90e2-81066277eb9b.png)

Legende Text auf Pfad:
![IKON-Legende-Interface-2](https://user-images.githubusercontent.com/44524000/70620403-74587080-1c17-11ea-85be-8b487fd25a15.png)
