### ISSUE TITLE
Uncertainty legend

### ISSUE THREAD

**Issue by ckinkeldey** [FUB-HCC/IKON-projektor#155]

**Comment by ckinkeldey** [comment]
variations as discussed

**Comment by avvinter** [comment]
![IKON-Interfacedesign-Multitouchdisplay-Legende-1-1](https://user-images.githubusercontent.com/44524000/72065496-aa544780-32de-11ea-9ca9-7cd805ece565.png)
![IKON-Interfacedesign-Multitouchdisplay-Legende-1-2](https://user-images.githubusercontent.com/44524000/72065497-aaecde00-32de-11ea-82ea-cd5120f718c0.png)
