### ISSUE TITLE
Largescreen-Version

### ISSUE THREAD

**Issue by ckinkeldey** [FUB-HCC/IKON-projektor#165]

**Comment by ckinkeldey** [comment]
Filters: only top categories
1) 4 Forschungsgebiete
2) Wissentransferaktivitäten
3) Sammlungen
4) Infrastruktur

**Comment by ckinkeldey** [comment]
Interaction:
Auswahl wie in Browser, aber auf long press
Hover wie im Broiwser, aber auf short press

**Comment by ckinkeldey** [comment]
Projektbeschreibungen in Sidebar ohne VIA-Link

**Comment by jessebenjamin** [comment]
[projektor-mtd.pdf](https://github.com/FUB-HCC/IKON-projektor/files/4124048/projektor-mtd.pdf)

**Comment by jessebenjamin** [comment]
please also try out this way

[projektor-mtd-2.pdf](https://github.com/FUB-HCC/IKON-projektor/files/4127501/projektor-mtd-2.pdf)

**Comment by mx-e** [comment]
#194 is the current issue for large-screen development, i'm closing this one
