### ISSUE TITLE
Highlight State

### ISSUE THREAD

**Issue by jessebenjamin** [FUB-HCC/IKON-projektor#179]
- [x] fix miscuing of state: currently, highlight only "stays" when clicking on selection again
- [x] selection should be cancelable by clicking anywhere in the vis

**Comment by mx-e** [comment]
- [ ] user should be able to highlight an entity (target group, infrastructure, collection, project) and all connected entities (including the connections) by hovering

- [ ] when unhovered the highlighting should be reset

- [ ] by clicking an entity the highlighting is made persistent even when the mouse leaves the entity

- [ ] by clicking on any non-entity are in the vis, the highlighting should reset

- [ ] the highlighting should persist in the url and be reloadable
