### ISSUE TITLE
Clusterview Uncertainty

### ISSUE THREAD

**Issue by jessebenjamin** [FUB-HCC/IKON-projektor#180]
- [x] default: uncertainty is NOT shown
- [x] add a checkbox for adding it on bottom right, adds uncertainty landscape + certainty scale.
- [x] if uncertainty is present, lines (projects/collections/wta) only appear on hover

**Comment by lillijo** [comment]
![Screenshot from 2020-02-04 14-36-16](https://user-images.githubusercontent.com/38139300/73749682-20bc5c00-475c-11ea-989f-c16a520fd466.png)


![Screenshot from 2020-02-04 14-35-57](https://user-images.githubusercontent.com/38139300/73749688-231eb600-475c-11ea-8793-3a6e7493ac4c.png)
