### ISSUE TITLE
Geoview Redesign

### ISSUE THREAD

**Issue by jessebenjamin** [FUB-HCC/IKON-projektor#188]
Reference picture attached

- [x] Add list of institutions with top 10 number of ktas incl. circle
- [ ] when circle is selected, show list of related ktas in the overlay
- [ ] hover: show institution in mini (continent) map below

- Redesign geoview below:
- [x] Arcs should be half-circles
- [ ] add green circle centrally above europe: on hover tooltip "Museum für Naturkunde"

**Comment by jessebenjamin** [comment]
![projektor-geo](https://user-images.githubusercontent.com/5793149/73668613-661e5200-46a6-11ea-930c-18afa1056ed2.png)

**Comment by mx-e** [comment]
i agreed with lily to take on highlighting as a priority

**Comment by lillijo** [comment]
![Screenshot from 2020-02-11 17-27-58](https://user-images.githubusercontent.com/38139300/74256618-ef133a00-4cf3-11ea-8f6e-4427ffcff7b7.png)
