### ISSUE TITLE
Filter-Chips

### ISSUE THREAD

**Issue by jessebenjamin** [FUB-HCC/IKON-projektor#19]
- [x] Überarbeitung der UI für Filter (cf neuer Screenshot)
- [x] Chips für FIltereinstellungen 
- [x] Filterauswahl generiert Breadcrumbs
- [x] breadcrumbs sind expandable für unterpunkte
- [x] Autocollapse (only one open)
- [x] scrollbar
- [x] Schrift abkürzen bei ca 30 chars
- [x] Tooltip für Chips mit Abkürzung

**Comment by jessebenjamin** [comment]
![filtern-neu](https://user-images.githubusercontent.com/5793149/36320093-51956dbe-1345-11e8-8060-b9f79c4df58f.jpg)
![filtern-neu2](https://user-images.githubusercontent.com/5793149/36320094-51bf3c02-1345-11e8-9854-423863a052b2.jpg)
![filtern-neu3](https://user-images.githubusercontent.com/5793149/36320095-51f1f98a-1345-11e8-991b-733fcfd44017.jpg)
![filtern-neu4](https://user-images.githubusercontent.com/5793149/36320096-521f621c-1345-11e8-9f95-7485af3124e3.jpg)

**Comment by jessebenjamin** [comment]
Bitte diese icons verwenden:



[Archive.zip](https://github.com/FUB-HCC/IKON-projektor/files/1732174/Archive.zip)

**Comment by coneissler** [comment]
<img width="1677" alt="bildschirmfoto 2018-02-18 um 11 55 56" src="https://user-images.githubusercontent.com/34349467/36351004-bffbb278-14a2-11e8-93dd-e80aed05100d.png">

**Comment by coneissler** [comment]
Das ist der Stand jetzt. Kannst du noch kurz umreißen, wie der Geldgeber Tab aussehen soll?

**Comment by jessebenjamin** [comment]
Cool. Mach es zunächst mal genauso wie die Forschungsbereiche, aber kleinere Schriftgröße (wenn die FBs 18px zB 12px) und im mittleren Systemfarbton. Danke
