### ISSUE TITLE
Make backend more compatible with windows

### ISSUE THREAD

**Issue by mx-e** [FUB-HCC/IKON-projektor#192]
Because the app is supposed to be run on Windows at the museum, it is important that the backend is fully able to be run on Windows and that the installation process is fairly painless. 
At the moment the execution part of this is elegantly ensured through Containerisation.

However, the build script is not optimised for any shell on Windows (for example git bash) and needs several modifications to run. For example: 
- an env variable to prevent a problem with some flags in the key-gen process
- changes to file/folder permissions (those apparently work differently on Windows)
(for used hot fixes see below) 

- [ ] adapt and test the shell script to make the install workflow as close to the one expected by the user from the install guide
- [ ] alternatively make an install guide specifically for Windows

![Photo](https://user-images.githubusercontent.com/13707737/74085159-6cca1200-4a76-11ea-8396-10bbe12fbf5c.jpg)
![Photo_1](https://user-images.githubusercontent.com/13707737/74085160-705d9900-4a76-11ea-80ca-735b445158fe.jpg)

**Comment by wittenator** [comment]
The plan is to not use a local deployment of the application on the touch pc in the museum since it poses a major maintenance burden.

**Comment by mx-e** [comment]
there needs to be a reasonably painless way to test the touch version of the front-end win an actual touch screen.

Is there any infrastructure for a production deployment of the backend, with a public (or for that matter password or somehow-else protected) way to access it ? 
How do i access it ? (Via ssh or physically ?)

**Comment by ckinkeldey** [comment]
It was our initial plan to have a version running at all times and make it accessible, e.g., via ssh or so. But we never got there. @wittenator wouldn't it be a good way of testing the deployment?

**Comment by wittenator** [comment]
Yeah, I can deploy a version on the free credits of GCP. Since there are a bootload of other features atm, I need a prioritisation from your side though

**Comment by wittenator** [comment]
I would just secure it via a basic auth in that case

**Comment by ckinkeldey** [comment]
Yes, it is high priority because of the testing phase. https://github.com/FUB-HCC/IKON-backend/issues/36
Thanks

**Comment by mx-e** [comment]
ill close this and make an issue for hosting over at backend
