### ISSUE TITLE
Firefox Bugs

### ISSUE THREAD

**Issue by jessebenjamin** [FUB-HCC/IKON-projektor#195]
(may overlap with general issues)

For branch: 168-slider+intro

Cluster-view:
- [x] uncertainty landscape is rendered badly
- [x] highlighting on hover of outer ring elements only works sporadically

Time-view:
- [x] upper part (list of KTAs) does not cut-off at 50%
- [x] graph titles overlap with axis labels (see screenshot)
- [x] tooltips are not rendered at the right y-height (see screenshot)

Geo-view:
- (waiting for new version)

Tutorial:
- [x] scrollbars to svg window and body are sometimes added, need to be suppressed

General:
- [x] breaks in lists in detail-panel are awkward (see screenshot)

**Comment by jessebenjamin** [comment]
<img width="1440" alt="Screen Shot 2020-02-10 at 13 36 21" src="https://user-images.githubusercontent.com/5793149/74150667-b0ee1b80-4c0a-11ea-8ddc-df428bbfa7ae.png">
<img width="1440" alt="Screen Shot 2020-02-10 at 13 31 04" src="https://user-images.githubusercontent.com/5793149/74150670-b21f4880-4c0a-11ea-955f-9509303645bc.png">

**Comment by mx-e** [comment]
Also 

An ongoing list of compatibility problems in Firefox
- [ ] cat titles not as expected
<img width="496" alt="Screenshot 2020-02-08 at 13 39 52" src="https://user-images.githubusercontent.com/13707737/74085375-b0be1680-4a78-11ea-8524-b07daf971c60.png">
