### ISSUE TITLE
Setup der Entwicklungsumgebung des Frontends  und  Implementierung der statischen HTML - Komponente

### ISSUE THREAD

**Issue by wittenator** [FUB-HCC/IKON-projektor#2]
- [x] Entwicklungsumgebung startet durch npm start oder ähnlichen Befehl
- [x] Komponenten Struktur definieren und festhalten
- [x] Alle Dependencies werden automatisch installiert
- [x] das Projekt kann durch npm run-devserver oder ähnlichen Befehl lokal gehostet werden
- [x] wenn man localhost aufruft erscheint die statische HTML-Seite
- [x] der Entwickler ist in der Lage in der HTML Seite eine neue Komponente zu rendern
- [x] Die statische HTML Seite sieht aus wie auf Bild allerdings ohne Navigationskomponenten, Petri-Dish und Logo (Farben für den Verlauf sind im Dokument <> im Ordner hinterlegt
- [x] Die Rendering Box für die Komponente überdeckt den gesamten Bildschirm
- [x] Das starten der Entwicklungsumgebung / evtl Installation ist in der Readme dokumentiert

**Comment by jessebenjamin** [comment]
![petri](https://user-images.githubusercontent.com/5793149/35108531-1c1918bc-fc74-11e7-9558-9c2bf36ee3d7.png)

**Comment by mx-e** [comment]
Also bei mir wurden nicht alle dependencies automatisch installiert, können wir das einfügen ?
