### ISSUE TITLE
Multitouch bugs & fixes

### ISSUE THREAD

**Issue by jessebenjamin** [FUB-HCC/IKON-projektor#220]
(arranged in order of priority, see photos for reference)

- [x] text-selection on long-press pops up, should be prevented OR we use doubletap
- [x] dragging time-filter opens "backwards" function of browser, should be prevented
- [x] side-panel does not extend to 100% on selection
- [x] the logo is again a png, please use svg as in browser (fixed in #219)

**Comment by jessebenjamin** [comment]
![IMG_5915](https://user-images.githubusercontent.com/5793149/76085955-64042780-5fb3-11ea-99af-8a8259745ddb.JPG)
![IMG_5914](https://user-images.githubusercontent.com/5793149/76085960-68304500-5fb3-11ea-8d72-4da060832bd7.JPG)
![IMG_5913](https://user-images.githubusercontent.com/5793149/76085965-68c8db80-5fb3-11ea-9f15-e1c1b3af0379.JPG)
![IMG_5912](https://user-images.githubusercontent.com/5793149/76085969-69fa0880-5fb3-11ea-9f4e-34899d2ffd15.JPG)
![IMG_5911](https://user-images.githubusercontent.com/5793149/76085970-6a929f00-5fb3-11ea-9f4c-5d970f62f94c.JPG)
![IMG_5910](https://user-images.githubusercontent.com/5793149/76085971-6b2b3580-5fb3-11ea-937e-51f84329fc02.JPG)

**Comment by mx-e** [comment]
logo was fixed in #219
