### ISSUE TITLE
Page name

### ISSUE THREAD

**Issue by ckinkeldey** [FUB-HCC/IKON-projektor#233]
<img width="306" alt="Screenshot 2020-04-28 14 12 24" src="https://user-images.githubusercontent.com/3234376/80485944-8e8eb300-895a-11ea-82c0-2e0caa6cf87c.png">

Please change to "MfN.projektor"

**Comment by lillijo** [comment]
so? 
![Screenshot from 2020-04-28 14-57-08](https://user-images.githubusercontent.com/38139300/80489773-9d786400-8960-11ea-8988-ada4c6c53367.png)

**Comment by ckinkeldey** [comment]
@jessebenjamin OK?

**Comment by jessebenjamin** [comment]
yes!
