### ISSUE TITLE
Interface Changes Zeit

### ISSUE THREAD

**Issue by jessebenjamin** [FUB-HCC/IKON-projektor#240]
- [x] get rid of missing data as part of the stacked graph
- [x] calculate the first year at which no new projects have been added to the data set
- [x] add a texture from that point on to the end of the graph, like attached image
- [x] texture could be done in css, so sth like this maybe, visually resembling the uncertainty landscape: https://codepen.io/jesbengradev/pen/pojrqdG
- [x] update sentence on missing data in tutorial "Der gemusterte Bereich zeigt hierbei an, dass noch nicht alle tatsächlich am MfN laufenden Projekte in dem VIA Wiki Datensatz vorliegen und unterstützt somit die Interpretation der Entwicklung der Forschungsgebiete." 
- [x] on hover of the texture area, tooltip with "Unsichere Datenlage"

![IMG_6440](https://user-images.githubusercontent.com/5793149/80695074-ab032a80-8ad5-11ea-9543-1d0af5948fe5.JPG)

**Comment by jessebenjamin** [comment]
example css:

.polka {
    background:
        radial-gradient(#989898 1px, transparent 2px),
        radial-gradient(#e8e8e8 1px, transparent 2px),
        #ffffff00;
    background-position: 0 0, 10px 10px;
    background-size: 20px 20px;
}

**Comment by lillijo** [comment]
so ? @jessebenjamin 
![Screenshot from 2020-04-30 14-10-07](https://user-images.githubusercontent.com/38139300/80709314-608da800-8aed-11ea-9a1b-906d52b51be0.png)

**Comment by jessebenjamin** [comment]
@lillijo looks great! but is there only one type of dot? in the css snippet there are two types of grayscale "pixels", which would connect it better to the uncertainty landscape visually i think

**Comment by jessebenjamin** [comment]
oh and is it possible to space them so they fit right onto the vertical lines of the other graphs?

**Comment by jessebenjamin** [comment]
second one! could you please change it to two gray-values please? one: #989898, two: #e8e8e8

**Comment by lillijo** [comment]
next try: 
![Screenshot from 2020-04-30 15-51-23](https://user-images.githubusercontent.com/38139300/80718493-80779880-8afa-11ea-991b-018df3165667.png)
