### ISSUE TITLE
Petri-Diagramm

### ISSUE THREAD

**Issue by wittenator** [FUB-HCC/IKON-projektor#3]
- [x] Diagramm muss Projektdaten aus dem State darstellen
 - [x] Dynamisches Updaten der Visualisierung (bei Filtern)
 - [x] Umschreiben der vorhandenen Komponente in React + Redux
 - [x] Komponente muss den ganzen Bildschirm ausfüllen
 - [x] Diagramm muss aber zentriert sein (so groß wie möglich)

**Comment by jessebenjamin** [comment]
![petri-projekt](https://user-images.githubusercontent.com/5793149/35108678-72964746-fc74-11e7-8855-c7f8c8a020a9.png)
![petri](https://user-images.githubusercontent.com/5793149/35108679-72c5b6b6-fc74-11e7-9afe-64fa4b404d59.png)

**Comment by JonasKopka** [comment]
Hi bin erst mal fertig mit dem Petri Dish so dass er funktioniert.
Ihr braucht nur das Aufrufen.
var n = new PetriDish(".svgGlobal",allProjectsJson);

n.updateData(halfprojectsjson);
[PieChart.txt](https://github.com/FUB-HCC/IKON-projektor/files/1724363/PieChart.txt)
[ProjectGraph.txt](https://github.com/FUB-HCC/IKON-projektor/files/1724364/ProjectGraph.txt)
[PetriDish.txt](https://github.com/FUB-HCC/IKON-projektor/files/1724365/PetriDish.txt)
