### ISSUE TITLE
Get Multitouch Working

### ISSUE THREAD

**Issue by jessebenjamin** [FUB-HCC/IKON-projektor#32]
- [x]  clean install for computer
- [x] which protocol to use? TUIO / windows touch?
- [x] do we need tuio.js?

**Comment by simon991** [comment]
Regarding libraries, evaluate the following:

- Name: QUO JS 
Events: Touch, Tap, Double tap, Hold, Fingers, Swipe, Swipe Up, Swipe Right, Swipe Down, Swipe Left, Drag
Other features: Built-in jQuery-like methods. It uses $$ to avoid conflict.
- Name: Hammer JS 
Events: Tap, Double tap, hold, drag, transform (pinch)
Other features: Javascript library focused only for multi-touch gestures
- Name: Touchy 
Events: long press, drag, pinch, rotate, swipe
Other features: jQuery plugin for webkit browsers and browsers that support outch events
Standlone: No, need jQuery framework
- Name: jQuery doubletap 
Events: Touch, Swipe, Tap, Double tap, Swipe left, Swipe Right, Swipe up, Swipe down
Other features: No android support yet
Standlone: No, need jQuery
- Name: jGestures 
Events: Orientation change, Pinch, Rotate, Swipe move, Swipe in multi direction, Swipe with 1,2,3 fingers, Tap with 1,2,3 fingers, pinch open, pinch close, shake in different directions
Other features: Bundled with many gestures and useful events
Standlone: No, need jQuery
- Name: Touch Swipe 
Events: Swipes in 4 directions, 1,2 fingers touch
Other features: Allows swiping and page scrolling
Standlone: No, need jQuery 
- Name: Touchable 
Events: Tap, Long Tap, Double tap, touchable move, touchable end
Other features: Unifies touch and mouse events

**Comment by simon991** [comment]
First attempt for multi-touch support using the hammer-js library can be found here: [https://github.com/FUB-HCC/IKON-projektor/commit/c1bd4039a1416b9c00c8e895695d44ac8d4dca46](https://github.com/FUB-HCC/IKON-projektor/commit/c1bd4039a1416b9c00c8e895695d44ac8d4dca46)
