### ISSUE TITLE
Timeline View

### ISSUE THREAD

**Issue by jessebenjamin** [FUB-HCC/IKON-projektor#33]
Paper prototyping see here: 
https://intern.hcc.mi.fu-berlin.de/confluence/display/IKON/2018-06-01+Prototyping

- [x] 4 disciplines / numPojects x Time
- [x] component in react app
- [x] d3 stuff in the component

**Comment by simon991** [comment]
Note: Since we integrated the new data, the old TimeLine.js produces errors for all projects with missing end date. All other projects are displayed as before.

**Comment by simon991** [comment]
Two interesting which helped me with the geo-view, maybe they help us with this timeline view as well:
https://medium.com/@Elijah_Meeks/interactive-applications-with-react-d3-f76f7b3ebc71
https://hackernoon.com/how-and-why-to-use-d3-with-react-d239eb1ea274
