### ISSUE TITLE
Geo View: first prototype with mocked data

### ISSUE THREAD

**Issue by jessebenjamin** [FUB-HCC/IKON-projektor#38]
- [x] figure out which framework to integrate into prototype (leaflet/d3/geojson vs topojson etc)
- [x] show institutions on a map in our prototype
- [x] show research areas (countries) on a map

http://geprisviz.imp.fu-berlin.de/
https://bost.ocks.org/mike/leaflet/
https://github.com/topojson

**Comment by jessebenjamin** [comment]
Draft for design vision

[Scannable Document on 12. Jul 2018 at 11_27_25 (1).pdf](https://github.com/FUB-HCC/IKON-projektor/files/2196934/Scannable.Document.on.12.Jul.2018.at.11_27_25.1.pdf)

**Comment by simon991** [comment]
Implemented a new version using the react-simple-maps library with some more features:
Branch: [https://github.com/FUB-HCC/IKON-projektor/compare/geo-visualization](https://github.com/FUB-HCC/IKON-projektor/compare/geo-visualization)
Commit: [https://github.com/FUB-HCC/IKON-projektor/commit/c9ae7cb5c3b26f99d75026d89f2aae79025d3f9f](https://github.com/FUB-HCC/IKON-projektor/commit/c9ae7cb5c3b26f99d75026d89f2aae79025d3f9f)

Implemented features (but only with static fake data):
- zooming

- panning

- selecting institutions and showing corresponding research areas

**Comment by simon991** [comment]
check out city data from here: [https://bl.ocks.org/curran/115407b42ef85b0758595d05c825b346](https://bl.ocks.org/curran/115407b42ef85b0758595d05c825b346)
