### ISSUE TITLE
Cluster View

### ISSUE THREAD

**Issue by jessebenjamin** [FUB-HCC/IKON-projektor#39]
- [x] topic view: tSNE/d3 clusters of topic extracted from projects' abstract 
- [x] display clusters using d3-polygon hull

**Comment by simon991** [comment]
Two interesting which helped me with the geo-view, maybe they help you with this issue as well:
[https://medium.com/@Elijah_Meeks/interactive-applications-with-react-d3-f76f7b3ebc71](https://medium.com/@Elijah_Meeks/interactive-applications-with-react-d3-f76f7b3ebc71)
[https://hackernoon.com/how-and-why-to-use-d3-with-react-d239eb1ea274](https://hackernoon.com/how-and-why-to-use-d3-with-react-d239eb1ea274)

**Comment by simon991** [comment]
![image](https://user-images.githubusercontent.com/23076879/45489287-2e86d100-b764-11e8-8862-704b702e94e4.png)

**Comment by wittenator** [comment]
Ahh, maybe we don't even need a Delauney Algorithm. We could also try to visualise the decision boundaries directly. (I am somewhat sure that it computes the same thing. Not sure how much SciPy does into that direction though). I can have a look.

**Comment by wittenator** [comment]
It could look like that https://i.ytimg.com/vi/PGy1rATkViA/maxresdefault.jpg

**Comment by simon991** [comment]
![image](https://user-images.githubusercontent.com/23076879/46149913-a3313380-c26b-11e8-9385-e610eb080619.png)
