### ISSUE TITLE
Zeitdiagramm

### ISSUE THREAD

**Issue by wittenator** [FUB-HCC/IKON-projektor#4]
- [x] Diagramm muss Projektdaten aus dem State darstellen
 - [x] Dynamisches Updaten der Visualisierung (bei Filtern)
 - [x] Umschreiben der vorhandenen Komponente in React + Redux
 - [x] Komponente muss den ganzen Bildschirm ausfüllen
 - [x] Diagramm muss aber zentriert sein (so groß wie möglich)

**Comment by jessebenjamin** [comment]
![process-projekt](https://user-images.githubusercontent.com/5793149/35109225-0beeff7c-fc76-11e7-8248-67822f2e2e36.png)
![process](https://user-images.githubusercontent.com/5793149/35109226-0c1d18da-fc76-11e7-91da-147b9f84a51e.png)

**Comment by JonasKopka** [comment]
Hier das Zeitdiagramm als .txt, da github kein .js dateien annimmt.
So wirds genutzt.
`var t = new TimeLine(".svgGlobal",allProjectsJson);
setTimeout(function(){
	t.updateData(halfProjectsJson);
},3000);
setTimeout(function(){
	t.updateData(allProjectsJson);
},6000);`
[TimeLine.txt](https://github.com/FUB-HCC/IKON-projektor/files/1689989/TimeLine.txt)
