### ISSUE TITLE
Geo View: enhance component by project details

### ISSUE THREAD

**Issue by simon991** [FUB-HCC/IKON-projektor#44]
- [x] lines are drawn between institutions and research areas. Instead, each line should represent one project (what if one project has multiple research areas -> multiple lines for the same project then? Or if project has no research area? -> not represented in the map then?)
- [x] open project popup when clicking on line

**Comment by jessebenjamin** [comment]
![geovis](https://user-images.githubusercontent.com/5793149/44209709-8da4f600-a164-11e8-8b8d-9d17ce55033c.png)
