### ISSUE TITLE
Entwicklung der Popover-Komponente

### ISSUE THREAD

**Issue by wittenator** [FUB-HCC/IKON-projektor#6]
- [x] Flexbox-Popover wird generiert aus Projektdaten
- [x] Aspect-Ratio der Popover-Box: 3 breit, 5 hoch (Richtwert höhe ca. 60% window)
- [x] Farbige Borders pro Box je nach Forschungsbereich-Bezug / default: mittlere Systemfarbe
- [x] Hintergrund der gesamten box ca. 80%-Opacity dunkle Systemfarbe
- [x] Default-Werte für alle nicht vorliegenden Daten
- [x] "Share"-Button neben/unterhalb Popover-Box ("mailto:")

![screen shot 2018-02-09 at 15 11 54 2](https://user-images.githubusercontent.com/5793149/36031620-9f5027fa-0dab-11e8-914e-b8c2b2db741b.png)

**Comment by jessebenjamin** [comment]
![screen shot 2018-02-09 at 15 17 17 2](https://user-images.githubusercontent.com/5793149/36031832-5e4ecbfc-0dac-11e8-8cbd-0c807267b308.png)
