### ISSUE TITLE
Three designs for cluster layout

### ISSUE THREAD

**Issue by ckinkeldey** [FUB-HCC/IKON-projektor#67]

**Comment by ckinkeldey** [comment]
![img_4192](https://user-images.githubusercontent.com/3234376/53403210-7ec0bb00-39b3-11e9-81dc-6c52b4607070.JPG)

**Comment by ckinkeldey** [comment]
![screen shot 2019-01-22 at 11 40 09 2](https://user-images.githubusercontent.com/3234376/53403543-2ccc6500-39b4-11e9-800d-4c96032bd6f3.png)

**Comment by ckinkeldey** [comment]
Three layouts with outer ring and three versions of clusters:
1) Like in the computed example but with hulls
2) ordered on a grid, rectangular fork
3) ordered on a grid but in circle form

**Comment by ckinkeldey** [comment]
[Clusterview.zip](https://github.com/FUB-HCC/IKON-projektor/files/2904847/Clusterview.zip)

**Comment by avvinter** [comment]
[Radialdiagramm-Präsentation.pdf](https://github.com/FUB-HCC/IKON-projektor/files/2905327/Radialdiagramm-Prasentation.pdf)

**Comment by ckinkeldey** [comment]
3. Variante
![screenshot 2019-03-04 10 10 12](https://user-images.githubusercontent.com/3234376/53722520-0ac85c00-3e66-11e9-948c-c61cd158a774.png)

**Comment by ckinkeldey** [comment]
[WTA-Zielgruppen.csv.zip](https://github.com/FUB-HCC/IKON-projektor/files/2925054/WTA-Zielgruppen.csv.zip)
Liste von Zielgruppen für Wissenstransfer

**Comment by avvinter** [comment]
![3 versions outer ring diagram](https://user-images.githubusercontent.com/44524000/53733118-37896d00-3e80-11e9-812b-0238fcd14692.png)

**Comment by ckinkeldey** [comment]
Aktuelles Prototyp-Design: 
![screenshot 2019-03-04 15 01 53](https://user-images.githubusercontent.com/3234376/53738102-96ee7980-3e8e-11e9-89a5-df086407a210.png)

**Comment by ckinkeldey** [comment]
![screenshot 2019-03-04 15 02 01](https://user-images.githubusercontent.com/3234376/53738116-9fdf4b00-3e8e-11e9-8284-3473dcfbefeb.png)
![screenshot 2019-03-04 15 01 56](https://user-images.githubusercontent.com/3234376/53738117-9fdf4b00-3e8e-11e9-85d6-09b8ad6fc709.png)

**Comment by ckinkeldey** [comment]
[hexagrid.zip](https://github.com/FUB-HCC/IKON-projektor/files/2926834/hexagrid.zip)

**Comment by avvinter** [comment]
![visualisation-layout-dark1](https://user-images.githubusercontent.com/44524000/53805189-c1e9d380-3f49-11e9-982a-35be75fc87b8.png)
![visualisation-layout-dark2](https://user-images.githubusercontent.com/44524000/53805201-c8784b00-3f49-11e9-9e42-50e5bf06e59c.png)

**Comment by avvinter** [comment]
What should the clusters look like in detail in a third sketch?
The initial post with analog sketch does not display any cluster building method.

**Comment by avvinter** [comment]
Design with polylines from the center of a cluster to different target groups.
![visualisation-layout-dark-group1](https://user-images.githubusercontent.com/44524000/53808760-5a388600-3f53-11e9-90ec-f1565521f1b0.png)
![visualisation-layout-dark-group2](https://user-images.githubusercontent.com/44524000/53808761-5a388600-3f53-11e9-8688-2a8dbaf5946b.png)

**Comment by avvinter** [comment]
Version with outline and lines from outline to target group instead of the center in the group.
![visualisation-layout-dark-group-outline](https://user-images.githubusercontent.com/44524000/53810198-b51fac80-3f56-11e9-8163-206ede6d35fb.png)

**Comment by ckinkeldey** [comment]
Merci!!
