### ISSUE TITLE
For presentation slide: principle of radial vis

### ISSUE THREAD

**Issue by ckinkeldey** [FUB-HCC/IKON-projektor#68]
Ring + clustered projects + some sample connections
Connections semi-transparent?

**Comment by ckinkeldey** [comment]
![grafik](https://user-images.githubusercontent.com/3234376/53412341-6bb8e580-39c9-11e9-9f8c-3ec1c3353ddf.png)

**Comment by avvinter** [comment]
![bildschirmfoto 2019-02-26 um 13 51 50](https://user-images.githubusercontent.com/44524000/53413923-bdfc0580-39cd-11e9-9614-a89bf510a67a.png)
