### ISSUE TITLE
Flächendiagramm

### ISSUE THREAD

**Issue by wittenator** [FUB-HCC/IKON-projektor#7]
- [x] Diagramm muss Projektdaten aus dem State darstellen
 - [x] Dynamisches Updaten der Visualisierung (bei Filtern)
 - [x] Umschreiben der vorhandenen Komponente in React + Redux
 - [x] Komponente muss den ganzen Bildschirm ausfüllen
 - [x] Diagramm muss aber zentriert sein (so groß wie möglich)

**Comment by jessebenjamin** [comment]
![terrain-projekt](https://user-images.githubusercontent.com/5793149/35109718-6d1f8310-fc77-11e7-9904-e0b25cb81c80.png)
![terrain](https://user-images.githubusercontent.com/5793149/35109719-6d673d36-fc77-11e7-95cb-57fd0dc95e60.png)
