### ISSUE TITLE
Review Interface Design

### ISSUE THREAD

**Issue by jessebenjamin** [FUB-HCC/IKON-projektor#70]
- [x] notes on font sizes, font families, layout
- [x] suggestions on improvements (minimum & maximum)

**Comment by jessebenjamin** [comment]
![screen shot 2019-03-05 at 14 20 55 2](https://user-images.githubusercontent.com/5793149/53808251-09745d80-3f52-11e9-8705-fa4ef7d0fd9a.png)
![screen shot 2019-03-05 at 14 21 02 2](https://user-images.githubusercontent.com/5793149/53808252-09745d80-3f52-11e9-84a9-bf9f84270bef.png)
![screen shot 2019-03-05 at 14 21 06 2](https://user-images.githubusercontent.com/5793149/53808254-09745d80-3f52-11e9-906a-9ddf00b0b44e.png)
![screen shot 2019-03-05 at 14 21 16 2](https://user-images.githubusercontent.com/5793149/53808255-09745d80-3f52-11e9-86cc-cb2200860c9d.png)

**Comment by avvinter** [comment]
Interface refinement step 3
![Interfacedesign-Webinterface-IKON](https://user-images.githubusercontent.com/44524000/56906374-63048e80-6aa2-11e9-9fb7-9c71ce216e70.jpg)

**Comment by avvinter** [comment]
![Interfacedesign-Webinterface-IKON-Refinement](https://user-images.githubusercontent.com/44524000/57150400-84c98280-6dce-11e9-82f5-586901de7e15.png)

**Comment by avvinter** [comment]
![Interfacedesign-Webinterface-IKON-Iteration-1](https://user-images.githubusercontent.com/44524000/57228074-3b1da980-7013-11e9-8c88-77313beb952b.png)
![Interfacedesign-Webinterface-IKON-Iteration-2](https://user-images.githubusercontent.com/44524000/57228075-3b1da980-7013-11e9-9f1e-25005ea40cd8.png)

**Comment by ckinkeldey** [comment]
![grafik](https://user-images.githubusercontent.com/3234376/57626130-9280c400-7595-11e9-8189-094ab8c2a7c2.png)

**Comment by avvinter** [comment]
When are sparklines visible? Allways or at a specific view?

**Comment by avvinter** [comment]
![Interfacedesign-Webinterface-IKON-Userscenario-1](https://user-images.githubusercontent.com/44524000/58021371-0299c780-7b0b-11e9-96ad-da9ac6ece3ca.png)

**Comment by avvinter** [comment]
![Interfacedesign-Webinterface-IKON-Userscenario-2](https://user-images.githubusercontent.com/44524000/58022627-20b4f700-7b0e-11e9-989c-2121bf1312ef.png)

**Comment by avvinter** [comment]
![Interfacedesign-Webinterface-IKON-Userscenario-3](https://user-images.githubusercontent.com/44524000/58023319-d03e9900-7b0f-11e9-8c18-ee68d4f4afac.png)

**Comment by avvinter** [comment]
![Interfacedesign-Webinterface-IKON-Userscenario-4](https://user-images.githubusercontent.com/44524000/58024948-a5564400-7b13-11e9-8d9d-f736804bfee6.png)

**Comment by avvinter** [comment]
![Interfacedesign-Webinterface-IKON-Userscenario-5](https://user-images.githubusercontent.com/44524000/58031734-4bf51180-7b21-11e9-8f07-4bd8fc53780b.png)

**Comment by avvinter** [comment]
![Interfacedesign-Webinterface-IKON-Userscenario-6](https://user-images.githubusercontent.com/44524000/58032233-7b584e00-7b22-11e9-82ed-3ea0d82ed6b8.png)
![Interfacedesign-Webinterface-IKON-Userscenario-7](https://user-images.githubusercontent.com/44524000/58032234-7b584e00-7b22-11e9-9af7-5c374bafd0c8.png)

**Comment by avvinter** [comment]
![Interfacedesign-Webinterface-IKON-Userscenario-8](https://user-images.githubusercontent.com/44524000/58032878-c3c43b80-7b23-11e9-9261-e499c2067bc7.png)
![Interfacedesign-Webinterface-IKON-Userscenario-9](https://user-images.githubusercontent.com/44524000/58032879-c45cd200-7b23-11e9-9dba-1533b1b3a7f1.png)

**Comment by avvinter** [comment]
![Interfacedesign-Webinterface-IKON-Userscenario-10](https://user-images.githubusercontent.com/44524000/58163105-b32ad700-7c83-11e9-85d6-abf058d5dd37.png)
![Interfacedesign-Webinterface-IKON-Userscenario-11](https://user-images.githubusercontent.com/44524000/58163106-b32ad700-7c83-11e9-98f9-00c0b79d34fa.png)
![Interfacedesign-Webinterface-IKON-Userscenario-12](https://user-images.githubusercontent.com/44524000/58163107-b3c36d80-7c83-11e9-9aa1-65d19636f70a.png)

**Comment by avvinter** [comment]
![Interfacedesign-Webinterface-IKON-Userscenario-13](https://user-images.githubusercontent.com/44524000/58165127-60ebb500-7c87-11e9-8341-6711e08e5a1e.png)
![Interfacedesign-Webinterface-IKON-Userscenario-14](https://user-images.githubusercontent.com/44524000/58165128-60ebb500-7c87-11e9-8e86-77e87bce19eb.png)

**Comment by avvinter** [comment]
![Interfacedesign-Webinterface-IKON-Userscenario-15](https://user-images.githubusercontent.com/44524000/58166651-95ad3b80-7c8a-11e9-9e02-c33fce4877ea.png)
![Interfacedesign-Webinterface-IKON-Userscenario-16](https://user-images.githubusercontent.com/44524000/58166652-9645d200-7c8a-11e9-9253-e383fc954aa0.png)

**Comment by avvinter** [comment]
![Interfacedesign-Webinterface-IKON-Userscenario-17](https://user-images.githubusercontent.com/44524000/58168968-d78cb080-7c8f-11e9-9893-269e9880b91b.png)

**Comment by avvinter** [comment]
![Interfacedesign-Webinterface-IKON-Development-1](https://user-images.githubusercontent.com/44524000/61377371-60e0ed80-a8a3-11e9-8172-50effebdad43.png)
![Interfacedesign-Webinterface-IKON-Development-2](https://user-images.githubusercontent.com/44524000/61377372-60e0ed80-a8a3-11e9-83fc-0bee8cf578c8.png)
![Interfacedesign-Webinterface-IKON-Development-3](https://user-images.githubusercontent.com/44524000/61377374-61798400-a8a3-11e9-896b-8fa264685043.png)

**Comment by avvinter** [comment]
sidebar width: 30.8 %

**Comment by avvinter** [comment]
![Interfacedesign-Webinterface-IKON-Development-4](https://user-images.githubusercontent.com/44524000/61381786-e23c7e00-a8ab-11e9-805e-4fac466cd520.png)
![Interfacedesign-Webinterface-IKON-Development-5](https://user-images.githubusercontent.com/44524000/61381787-e2d51480-a8ab-11e9-8453-152e5e4c95f4.png)

**Comment by avvinter** [comment]
![Interfacedesign-Webinterface-IKON-Development-6](https://user-images.githubusercontent.com/44524000/61385635-0a7bab00-a8b3-11e9-8152-f2a9dc300e6f.png)
