### ISSUE TITLE
Cluster view: Integrate infrastructure

### ISSUE THREAD

**Issue by ckinkeldey** [FUB-HCC/IKON-projektor#71]

**Comment by ckinkeldey** [comment]
In addition to research projects and target groups, we need to integrate infrastructure between them. 
Since the radial layout does not work anymore, we should try a semicircle layout in three versions:
 
![sketch_190311](https://user-images.githubusercontent.com/3234376/54142128-57dc9d00-4427-11e9-8d2d-7052a5fe76da.jpg)

**Comment by ckinkeldey** [comment]
Please try to integrate the icons from https://intern.hcc.mi.fu-berlin.de/confluence/download/attachments/40932327/IKON-ICONS.zip?api=v2
![infrastructure-sketch](https://user-images.githubusercontent.com/3234376/54142189-7a6eb600-4427-11e9-970a-278ab6157d9b.png)

**Comment by avvinter** [comment]
![Visualisation-Layout-Doubleshape-1](https://user-images.githubusercontent.com/44524000/54198795-a5a8e200-44c7-11e9-8140-37b89534a3e8.png)
![Visualisation-Layout-Doubleshape-2](https://user-images.githubusercontent.com/44524000/54198796-a5a8e200-44c7-11e9-81f6-cfde7afe6a49.png)
![Visualisation-Layout-Doubleshape-3](https://user-images.githubusercontent.com/44524000/54198797-a5a8e200-44c7-11e9-8a84-ddfa892b1ce1.png)

**Comment by avvinter** [comment]
Here comes the sun
![Visualisation-Layout-Doubleshape-4](https://user-images.githubusercontent.com/44524000/54199355-fe2caf00-44c8-11e9-8a85-5377c411d468.png)

**Comment by ckinkeldey** [comment]
Zur Zei im Wiki:
33 Sammlungen
22 Labore / Großgeräte

Also 55, das ist schwer darzustellen, vielleicht können wir sie noch zusammenfassen.

**Comment by ckinkeldey** [comment]
![grafik](https://user-images.githubusercontent.com/3234376/54525314-36723880-4974-11e9-8070-dcb78d8bf7e1.png)

**Comment by ckinkeldey** [comment]
Pls try circles as well:

![grafik](https://user-images.githubusercontent.com/3234376/54526148-307d5700-4976-11e9-988d-98e957270f79.png)
