### ISSUE TITLE
Refine "Visualisation-Layout-Halfcircle-Radialgroups"

### ISSUE THREAD

**Issue by ckinkeldey** [FUB-HCC/IKON-projektor#73]
Remove numbers
Increase font size for labels

**Comment by avvinter** [comment]
Dropped refined version of  "Visualisation-Layout-Halfcircle-Radialgroups" as "Visualisation-Layout-Halfcircle-Radialgropus-Refined" in the ikon-design box repo.

**Comment by ckinkeldey** [comment]
Nice
