### ISSUE TITLE
New Design for Infrastructure-Icon

### ISSUE THREAD

**Issue by jessebenjamin** [FUB-HCC/IKON-projektor#74]
- [x] develop icon-drafts based on existing iconography

**Comment by jessebenjamin** [comment]
@avvinter du kannst dir die forschungsgeräte im wiki angucken, login im confluence

**Comment by avvinter** [comment]
Dropped three first designs in the fu box ikon-design repo: https://box.fu-berlin.de/apps/files/?dir=/ikon-design&fileid=9230714

**Comment by avvinter** [comment]
![Testserie-Icon](https://user-images.githubusercontent.com/44524000/55737062-cf9ce800-5a24-11e9-9cf8-0553475b42e6.png)

**Comment by ckinkeldey** [comment]
Jesse: "4. von rechts"

**Comment by avvinter** [comment]
![Iconapplicationtest-dark](https://user-images.githubusercontent.com/44524000/56281922-23d35680-610e-11e9-95c8-f7e0a1cb0855.png)

**Comment by avvinter** [comment]
[Infrastruktur-Refined.pdf](https://github.com/FUB-HCC/IKON-projektor/files/3173324/Infrastruktur-Refined.pdf)
