### ISSUE TITLE
IKON slider image

### ISSUE THREAD

**Issue by jessebenjamin** [FUB-HCC/IKON-projektor#80]
slider image for project IKON for the HCC website

**Comment by avvinter** [comment]
![Wissenschaft+Gesellschaft-1](https://user-images.githubusercontent.com/44524000/57627221-e096c700-7597-11e9-8003-9d7817eff97f.jpg)
![Wissenschaft+Gesellschaft-2](https://user-images.githubusercontent.com/44524000/57627222-e12f5d80-7597-11e9-8322-a7c7f477ea45.jpg)

**Comment by ckinkeldey** [comment]
![ikon-clusterview](https://user-images.githubusercontent.com/3234376/58427543-355e3580-80a0-11e9-933d-958d7f3a87da.png)

**Comment by ckinkeldey** [comment]
![grafik](https://user-images.githubusercontent.com/3234376/58428218-1496df80-80a2-11e9-80b9-961beac19d81.png)

**Comment by ckinkeldey** [comment]
Preliminary IKON logo?

**Comment by avvinter** [comment]
![IKON-Websliderimage](https://user-images.githubusercontent.com/44524000/58429908-ab19cf80-80a7-11e9-8732-9338364096d0.png)

**Comment by avvinter** [comment]
[IKON-Websliderimage-withlogo.pdf](https://github.com/FUB-HCC/IKON-projektor/files/3281040/IKON-Websliderimage-withlogo.pdf)
[IKON-Websliderimage-withoutlogo.pdf](https://github.com/FUB-HCC/IKON-projektor/files/3281041/IKON-Websliderimage-withoutlogo.pdf)

**Comment by avvinter** [comment]
![IKON-Websliderimage-withlogo](https://user-images.githubusercontent.com/44524000/59347047-fa9d0400-8d13-11e9-8e91-f9a381dbee66.png)
![IKON-Websliderimage-withoutlogo](https://user-images.githubusercontent.com/44524000/59347048-fa9d0400-8d13-11e9-99a9-531a7a3f6645.png)
