### ISSUE TITLE
Erstelle Routing

### ISSUE THREAD

**Issue by wittenator** [FUB-HCC/IKON-projektor#9]
- [x] Kodiere View(der 3 Visualisierungen) und Filter in der URL
- [x] Durch einfügen der entsprenden URL, erscheint der durch die URL beschriebene State
- [x] Änderungem im State bezgl. Filter und View werden in der URL übernommen

**Comment by joetm** [comment]
Ich hatte erwartet, dass ihr react-router verwendet.
Das würde viel schönere URLs produzieren, z.B. /petri/

Die vielen URL-Parameter sind sehr unschön.
Ich verstehe nicht, warum die mitgeschleppt werden müssen - zumindest bei der Standardnavigation (ohne Filterung) ändern sie sich sowieso nicht.

Für die Filterung könnte man überlegen, die Parameter zu kodieren. Z.B. wie die Parameter bei Street View. Oder durch die Verwendung von bitwise-Operationen.

**Comment by mx-e** [comment]
Hi Jonas,

react.router ist geplant für den Wechsel zwischen verschiedenen Pages (noch nicht implementiert) also zwischen ‘Entdeckungen' und ‘Erkunden’ also als Top-Level Navigation:


Ich gebe dir recht, die Url-Attribute sind nicht schön, es ist auch geplant sie erheblich zu minifizieren (3-4 Zeichen/Attribut), allerdings sind sie zu einem gewissen grad nötig um eindeutig alle aktivierten Filter, den ausgewählten Graphen und das geöffnete Popover zu übertragen.

In der GraphView Komponente haben wir uns gegen Router entschieden, da ein Conditional Render hier unkomplizierter ist (3 Statelose Komponenten, die die selben Inputs haben weitgehend). Die Information welche Visualisierung gerade angezeigt wird, sollte am Ende ungefähr 3 Zeichen lang sein.

Bitweise Kodierung ist im Moment nicht im Scope, ist aber mit Sicherheit eine elegantere Kodierung, können wir gerne beim nächsten Sprinttreffen noch einmal drüber reden.

Viele Grüße,

Max
